In [1]:
import numpy as np

Data

In [ ]:
U1 = np.array([
    [0, 0, 1, 0, 0],
    [0, 1, 0, 0, 0],
    [0, 0, 0, 1, 0],
    [1, 0, 0, 0, 0],
    [0, 0, 0, 0, 1],
    [0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0]
])

U2= np.array([
    [0, 0, 0, 1],
    [1, 0, 0, 0],
    [0, 0, 1, 0]
    ])

U3 = np.array([
    [0, 0, 1, 0, 0, 0],
    [0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0],
    [1, 0, 0, 0, 0, 0]
])

G = np.array([
    [[ 7,  1,  9,  5,  4,  2],
     [ 3,  8,  5,  6, 10,  7],
     [ 1,  4,  2,  9,  6,  8],
     [ 5, 10,  7,  3,  1,  9]],

    [[ 6,  3,  1,  8, 10,  4],
     [ 9,  2,  5,  7,  3,  6],
     [ 1,  4, 10,  2,  5,  9],
     [ 8,  7,  3,  6,  9,  1]],

    [[ 4,  9,  3,  7,  1,  6],
     [ 8,  2, 10,  5,  9,  3],
     [ 6,  1,  4,  8,  2, 10],
     [ 5,  7,  9,  3, 10,  1]],

    [[ 2,  5, 10,  1,  8,  6],
     [ 7,  3,  9,  4,  5,  2],
     [ 1,  6,  8,  3,  4, 10],
     [ 9,  2,  5,  7, 10,  3]],

    [[ 8,  4,  6,  9,  3,  7],
     [ 5, 10,  1,  2,  8,  4],
     [ 2,  7,  9,  5,  1,  6],
     [ 3,  6,  4, 10,  7,  9]]
])

In [11]:
def construct_T(U1, U2, U3, G):
    n1=U1.shape[0]
    n2=U2.shape[0]
    n3=U3.shape[0]
    r1=U1.shape[1]
    r2=U2.shape[1]
    r3=U3.shape[1]

    rx=G.shape[0]
    ry=G.shape[1]
    rz=G.shape[2]

    if(r1!=rx or r2!=ry or r3!=rz):
        print("Incompatible dimensions between U and G")
        return None
    T=np.zeros((n1,n2,n3))
    for i1 in range(n1):
        for i2 in range(n2):
            for i3 in range(n3):
                sum=0
                for j1 in range(r1):
                    for j2 in range(r2):
                        for j3 in range(r3):
                            sum+=U1[i1,j1]*U2[i2,j2]*U3[i3,j3]*G[j1,j2,j3]
                T[i1,i2,i3]=sum
    return T

    
    

In [12]:
T=construct_T(U1,U2,U3,G)
print(T)

[[[ 9.  7.  3.  5.]
  [ 3.  9.  7.  4.]
  [ 4.  1.  8.  6.]]

 [[ 3.  7.  6.  8.]
  [ 1.  3.  8.  6.]
  [10.  4.  2.  1.]]

 [[ 5.  2.  7.  9.]
  [10.  5.  1.  2.]
  [ 8.  6.  3.  1.]]

 [[ 7. 10.  3.  5.]
  [ 9.  1.  5.  7.]
  [ 2.  4.  9.  1.]]

 [[ 4.  6. 10.  3.]
  [ 6.  4.  9.  8.]
  [ 9.  7.  5.  2.]]

 [[ 9.  7.  3.  5.]
  [ 3.  9.  7.  4.]
  [ 4.  1.  8.  6.]]

 [[ 7. 10.  3.  5.]
  [ 9.  1.  5.  7.]
  [ 2.  4.  9.  1.]]]
